name: Build

on:
  push:
    branches:
      - cmp-rewrite
  pull_request:
    branches:
      - cmp-rewrite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Gradle build
        run: ./composeApp/gradlew build